### ISSUE TITLE
Never prompts for audio

### ISSUE THREAD

**Issue by megamindbrian** [Kaljurand/dictate.js#12]
Just sits on waiting for audio input without prompting.  Using the latest Chrome.

**Comment by ghost** [comment]
_

**Comment by Kaljurand** [comment]
Please be more specific in your bug report.

**Comment by ghost** [comment]
_

**Comment by Kaljurand** [comment]
As I said, please be more specific. E.g. are you talking about these default settings:

https://github.com/Kaljurand/dictate.js/blob/409e89a2659e4a8104db25b2143b529793fe6cef/lib/dictate.js#L4-L6

or some links in the documentation?

**Comment by megamindbrian** [comment]
Links in documentation?
