### ISSUE TITLE
It is not showing my kaldi words

### ISSUE THREAD

**Issue by lio14cha** [Kaljurand/dictate.js#17]
I tried the demo.html. But it is not following my kaldi words. How to connect it to my own ASR. how to configure this demo.html. It is showing like
msg: 10: 1005//true
msg: END OF SESSION: 
msg: 8: {"status": 0, "adaptation_state": {"type": "string+gzip+base64", "id": "71d55971-c898-402f-b0f6-5dda543b487c", "value": "eJzdWk1PGzEQvedX7B1hbI/HY0tRpAqVqlJbWtEb4rCFRYpKErQEhPrrO7u2UyhfCdlkdyMkMh7PvPdmPOuTh8fTq/G0+HxXnM9n5cf7eZlXxoeL/Hqez8ez6Qn/FKNseDi5W9gh56Hn5LrIfxdlct2Msuw0OxsMP13NfuVXj9yDLDMC0TtT7CnJttHO2WJPUraPQhsJjhc+U4JQEtU2b6B2oMPCCkAPKixIaCSKC1PlaJdyFAD4sNBCeeeqMJftgwDjMNFISToig3ASrY0bXhntQ4YW3npMQWTJuLRBSHGHoYC8CRuqUpz84CB4rXBKUW2z11qnU7Q2SJAwq/J83RLWDcosMJ30EKJAWA2eUkHKgw2SjFCEOlbK3ZVIYaGFc4YWG1orchFKgY42cxgmx5hBNnGzKHJRrhHOA8Yz40KBTOyTF9ryefDC1m1Wyoc66iP3to6qJ4DAEbMozSxSomN6pSqNYCmaoI2GaBM3OYRw+xFQR9sQUIr3KE10Sy9t9CqOTuBgvV34PTeztrmtDiNTdSpgMdraSx8gPTdSVeXzyDruMI9GHF/ue40vmVajsqq2lbBcexhxz6NglalnoVKpdJhqzvUKXJwGBQaiiVx5COdT5jEK08lj770Kw+mEQSsXY0emmvOaVkuLmGyEalpqG7SCJA2QxyXFGE8m2jy+BmOJhCZ+FSSQD8VGDRK8TfIdmKiHSycZvyhZffhH5exPka6HcBccPL024rUT74bh47voZj6eLK6gavt7OZ6Vx5eXN8V8lFnJZaDPhl/z+8PZ7ZRdSsps+O12clTmk4ITePXjNr8oGeT8Z1FORnz5qGzAlVb/Fj8PjEfmf4sny2ccz7pecL7ofmXj1a03Nt/cXiJgqZAlg5YOWyFwpdAVg1cOf0fCu1LemfTutDUS10pdM3nt9AYAGoFoCKQxmAaBGoVqGKxxuA0AbgRyQ6Abg90g8EahNwy+cfgtEGyFYkskW6PZItFWqbZMtnW6FghboWyJtDXaFolbpW6ZvHX6DgjohISOiOiMjA4J6ZSUjonpnJwOCuqkpI6K6qysDgvrtLSOi+u8vB4I7IXEnojsjcweCe2V1J6J7Z3cHgrupeSeiu6t7B4L77X0novvvfwdKGAnStiRInamjKqQs8Hwy3ha5GV455edLt4Htq2tmb9/zydffB15sORL7r+e9Zxq", "time": "2018-08-01T08:13:38"}, "id": "71d55971-c898-402f-b0f6-5dda543b487c"}
msg: 7: Send tag: EOS
msg: 5: Send: blob: audio/x-raw, 2972
msg: END OF SPEECH: 
msg: 11: Stopped recording
msg: 5: Send: blob: audio/x-raw, 8916
msg: 5: Send: blob: audio/x-raw, 8918
msg: 5: Send: blob: audio/x-raw, 5944
msg: 5: Send: blob: audio/x-raw, 8916
msg: 5: Send: blob: audio/x-raw, 8916
msg: 5: Send: blob: audio/x-raw, 5944
msg: 9: [object Event]
msg: READY FOR SPEECH: 
msg: 3: Recorder initialized
msg: 2: Media stream created
msg: 1: Waiting for approval to access your microphone ...
after speaking.No output text is presenting on the textarea. Some times some unusual words are presenting.
Thank you.

**Comment by Kaljurand** [comment]
You seem to be connected to the Kaldi server because adaptation_state is returned. More details are needed to debug this further. Does the server work, e.g. can you use it with the official client Python script? Does recording in the browser work, e.g. can you use speech recording/recognition with some other webservices?

**Comment by alexanderwebber** [comment]
Also having this same issue. 

Headset works properly with the demo found at https://bark.phon.ioc.ee/dictate/. 

Server works fine, correct output from TED talk videos. 

Neither mob.html nor demo.html is recognizing speech.

This is the output for mob.html using the default server settings within the mob.html on your website:

msg: 10: 1005//true
msg: END OF SESSION: 
ERR: 4: Server error: 1: No speech
msg: 11: Stopped recording
msg: 8: {"status": 1}
msg: 9: [object Event]
msg: READY FOR SPEECH: 
msg: 3: Recorder initialized
msg: 2: Media stream created
msg: 1: Waiting for approval to access your microphone ...
