### ISSUE TITLE
Navigator.getUserMedia() is deprecated

### ISSUE THREAD

**Issue by niranjanviladkar** [Kaljurand/dictate.js#6]
Deprecated use at location : https://github.com/Kaljurand/dictate.js/blob/master/lib/dictate.js#L103
Reference : https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

The reference webpage suggests : "Please use MediaDevices.getUserMedia() in new applications."

**Comment by Kaljurand** [comment]
Fixed by https://github.com/Kaljurand/dictate.js/pull/27
