### ISSUE TITLE
No live audio input in this browser: [object NavigatorUserMediaError]

### ISSUE THREAD

**Issue by kaituoxu** [Kaljurand/dictate.js#7]
Hi, when I run the demo in my server by
```python
python -m SimpleHTTPServer 2345
```
and I visit it in another computer in chrome by `(server's ip):2345/mob.html`

but I got an error like below, it can not prompt me to access microphone.

```bash
ERR: 5: No live audio input in this browser: [object NavigatorUserMediaError]
msg: 1: Waiting for approval to access your microphone ...
```

can you help me to point out where did I go wrong?
Thx.
 : )

**Comment by skoocda** [comment]
Chrome requires an SSL connection to access your microphone, by default. It saves the user's input- so when a user accesses the page later, Chrome does not request microphone access again.

Your configuration should work in Firefox, however.

**Comment by Kaljurand** [comment]
Confirming what @skoocda wrote: you can use Firefox with your current setup, for Chrome you would need to serve the demo via https.

I've experimented with Firefox 50.0.2 and Google Chrome 55.0 on Ubuntu 16.04, serving `dictate.js` from my Raspberry Pi at 192.168.0.11.

*Firefox*

- on the server, start: ``python -m SimpleHTTPServer 2345``
- on the client, go to: ``http://192.168.0.11:2345/demos/mob.html``

*Google Chrome*

Follow the instructions https://gist.github.com/dergachev/7028596 to start a https-server, i.e. generate server.pem (just leave all the fields at their default values):

```
openssl req -new -x509 -keyout server.pem -out server.pem -days 365 -nodes
```

and start this Python program:

```
import BaseHTTPServer, SimpleHTTPServer
import ssl
httpd = BaseHTTPServer.HTTPServer(('192.168.0.11', 4443), SimpleHTTPServer.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./server.pem', server_side=True)
httpd.serve_forever()
```
On the client, go to https://192.168.0.11:4443/demos/mob.html

(Sorry for taking so long to respond.)
